# Generated by Django 5.1.1 on 2024-10-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_ingredients_delete_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(help_text='Price in Vietnamese Dong (VND)'),
        ),
    ]
