# Generated by Django 5.1.1 on 2024-10-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_cruelty_free',
            new_name='has_oil',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_oil_free',
        ),
        migrations.AlterField(
            model_name='product',
            name='is_natural_organic',
            field=models.CharField(max_length=100),
        ),
    ]
