# Generated by Django 5.1.1 on 2024-10-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_is_cruelty_free_product_has_oil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recommended_age',
        ),
        migrations.AlterField(
            model_name='product',
            name='avg_rating',
            field=models.FloatField(default=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_natural_organic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
