# Generated by Django 5.1.1 on 2024-10-04 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='default_pfp.jpg', null=True, upload_to='profile_pics/')),
                ('skin_elasticity', models.CharField(max_length=50)),
                ('skin_texture', models.CharField(max_length=50)),
                ('acne_proneness', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skin_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.skintype')),
            ],
        ),
    ]
