# Generated by Django 5.1.1 on 2024-10-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subscriptiontier_remove_profile_skin_elasticity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_pfp.png', null=True, upload_to='profile_pics/'),
        ),
    ]
