# Generated by Django 5.1.1 on 2024-10-23 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkincareAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('skin_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.skintype')),
            ],
        ),
    ]
