# Generated by Django 5.1.1 on 2024-10-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_skincareadvice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skincareadvice',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
