# Generated by Django 5.1.1 on 2024-10-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_skincareadvice_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skincareadvice',
            old_name='skin_types',
            new_name='skin_type',
        ),
    ]
