# Generated by Django 5.1.1 on 2024-11-04 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_skincareadvice_skin_type_dailycheckin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckin',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
